"""add updated_at and indexes

Revision ID: 0e971092c2d0
Revises: 80af58a3ad83
Create Date: 2026-06-21 00:48:17.469551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e971092c2d0'
down_revision: Union[str, Sequence[str], None] = '80af58a3ad83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_captures_user_id', 'captures', ['user_id'], unique=False)
    op.create_index('idx_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_index('idx_notion_databases_user', 'notion_databases', ['user_id'], unique=False)
    op.add_column('reminders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_reminders_remind_at', 'reminders', ['remind_at', 'is_sent'], unique=False)
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_user_status', table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_index('idx_reminders_remind_at', table_name='reminders')
    op.drop_column('reminders', 'updated_at')
    op.drop_index('idx_notion_databases_user', table_name='notion_databases')
    op.drop_index('idx_messages_user_id', table_name='messages')
    op.drop_index('idx_captures_user_id', table_name='captures')
    # ### end Alembic commands ###
